AllCops:
  # Include gemspec and Rakefile
  Include:
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - Rakefile
    - Gemfile
    - '*.gemspec'
  DisplayCopNames: true
  StyleGuideCopsOnly: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SignalException:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false